# Generated by Django 5.1.5 on 2025-01-28 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_alter_tag_name'),
    ]

    operations = [
    ]
